---
author: "Sven Werenbeck-Ueding"
format: 
  pdf:
    fontsize: 10pt
    mainfont: "Latin Modern Roman"
    sansfont: "Latin Modern Roman"
    monofont: "Latin Modern Mono"
    fontfamily: lmodern
    pdf-engine: xelatex
    margin-left: 2.5cm
    margin-right: 2.5cm
    margin-top: 2.5cm
    margin-bottom: 2cm
    linestretch: 1.5
    include-in-header:
      text: |
        %\usepackage[paperheight=297mm, paperwidth=210mm,% Set the height and width of the paper
        %  includehead,% See below for an explanation
        %  nomarginpar,% We don't want any margin paragraphs
        %  textwidth=16cm,
        %  headheight=16pt % Set \headheight to 16pt to avoid fancyhr warnings
        %]{geometry}
        \newlength{\datecolumn}
        \setlength{\datecolumn}{3cm} % defines length for first column in table
        \newlength{\othercolumn}
        \setlength{\othercolumn}{13cm}
        \usepackage{fancyhdr}
        %\setlength{\headheight}{2.5cm}
        \usepackage{fontawesome5}
---

\pagestyle{fancy}
\fancyhead{}

\fancyhead[c]{
\Large Sven Werenbeck-Ueding\hfill Curriculum Vitae
}

\fancyfoot[r]{
Last updated: \today
}

\begin{tabular}{ll}

\faAddressBook[regular] & Ruhr University Bochum\\
& Faculty of Management \& Economics\\
& Universitätsstraße 150\\
& D-44801 Bochum\\
& Germany\\

\faEnvelope[regular] & \href{mailto:sven.werenbeck-ueding@ruhr-uni-bochum.de}{sven.werenbeck-ueding@rub.de}\\
\faPhone & +49 (0) 234 32-27523\\
\faGlobe & \href{https://werenbeck-ueding.github.io/}{https://werenbeck-ueding.github.io/}\\

\end{tabular}


<!-- ## Resarch Interests -->

<!-- \begin{tabular}{p{\datecolumn}p{\othercolumn}} -->
<!--    & \textbf{Applied Microeconometrics, Spatial Economics, Education Economics}\\ -->
<!-- \end{tabular} -->


## Employment

<!--Positions & Affiliations-->

\begin{tabular}{p{\datecolumn}|p{\othercolumn}}
  Since 10/2021 & \textit{Research Assistant}, Chair of Empirical Economics, Ruhr University Bochum \\
  11/2021 -- 12/2024 & \textit{External Consultant / Product Owner} (self-employed; client: adesso SE) \\
  01/2021 -- 09/2021 & \textit{Student Assistant} (Business Analysis in Software Development; Line of Business: Banking), adesso SE, Dortmund \\
  10/2019 -- 06/2020 & \textit{Student Assistant}, Chair of Statistics / Econometrics, Ruhr University Bochum \\
  02/2018 -- 09/2018 & \textit{Military Service}, Mountain Engineer Battalion 8, Ingolstadt \\
  10/2015 -- 03/2016 & \textit{Student Assistant} (Tax Department), GFKL Financial Services AG, Essen \\
\end{tabular}


## Education

\begin{tabular}{p{\datecolumn}|p{\othercolumn}}
  \textit{Ongoing} & \textit{PhD} in Management \& Economics, Ruhr University Bochum\\
  & Supervisor: Prof. Dr. Thomas K. Bauer (Ruhr University Bochum, RWI, IZA)\\
  & Co-Supervisor: Prof. Dr. Dr. h.c. Christoph M. Schmidt (Ruhr University Bochum, RWI)\\
  10/2018 -- 10/2021 & \textit{Master of Science} in Management \& Economics, Ruhr University Bochum\\
  10/2014 -- 09/2017 & \textit{Bachelor of Science} in Management \& Economics, Ruhr University Bochum\\
  %08/2006 -- 06/2014 & \textit{Abitur}, Annette-von-Droste-Hülfshoff Gymnasium Dülmen
\end{tabular}


## Affiliations

\begin{tabular}{p{\datecolumn}|p{\othercolumn}}
  Since 04/2023 & \textit{Guest Researcher}, Department of Labor Markets, Education, Population at RWI -- Leibniz-Institute for Economic Research\\
\end{tabular}


## Research

\textbf{Working Paper:}

\textit{``Heterogeneous Trends in Apartment Rental Prices"} (with Maike Metz-Peeters). 2025. \textit{Ruhr Economic Papers}, 1156.

\textbf{Work in Progress:}

\textit{``Local Childcare Access and Local Employment"}

\textit{``Unintended Consequences? The Effects of a Place-based Policy on Firm Market Power"} (with Kevin L. Berlet and Mirko Titze)

\textit{``Lost in Translation. Information Frictions in School Track Choice -- Evidence from a Randomized Field Experiment"} (with Friederike Hertweck, Pia Schilling, and Moritz Welz). AER Registration: AEARCTR-0011821.


## Conferences & Presentations

\begin{tabular}{p{\datecolumn}|p{\othercolumn}}
  2022 & 61st ERSA Conference
\end{tabular}


## Teaching Experience

\begin{tabular}{p{\datecolumn}|p{\othercolumn}}
\multicolumn{2}{l}{Ruhr University Bochum:} \\
2025            & Tutorial ``Introduction to Microeconometrics'' (Master) \\
2024            & Seminar ``Empirical Economics'' (Bachelor) \\
                & Seminar ``Economics of Migration'' (Master) \\
                & Lecture ``Data Analysis Using R'' (Master) \\
2023            & Tutorial ``Labor Economics'' (Master) \\
                & Lecture ``Data Analysis Using R'' (Master) \\
2021 -- 2022    & Tutorial ``Applied Empirical Economics'' (Bachelor) \\
                & Tutorial ``Labor Economics'' (Master) \\
2019 -- 2020    & Tutorial ``Statistics II'' (Bachelor) \\
\end{tabular}


## Languages

\begin{tabular}{p{\datecolumn}p{\othercolumn}}
   & German (native), English (fluent)
\end{tabular}


## Technical Skills

\begin{tabular}{p{\datecolumn}p{\othercolumn}}
   \textbf{Programming:} & R (proficient), Python (basic), Stata (basic)\\
   \textbf{Typewriting:} & Quarto, \LaTeX\\
   \textbf{Other:} & Git
\end{tabular}
